- name: make sure to install apache2 on machine
  yum:
    name: "{{ package_name }}"
    state: latest
    update-cache: yes
- name: make sure to run the apache
  service:
    enabled: yes
    name: "{{ service_name }}"
    state: started
- name: copy the index.html to /var/www/html
  copy:
    src: "{{ index_file }}"
    dest: "{{ dest_path }}/{{ index_file }}"
  notify: Restart Apache
