- hosts: all
  become_user: root
  become_method: sudo
  become: yes

  tasks:
   - name: make sure to install apache2 on ubuntu machine
     apt:
       name: apache2
       state: latest
       update-cache: yes
     when: ansible_distribution=="Ubuntu"

   - name: make sure to install httpd on redhat machine
     yum:
      name: httpd
      state: latest
      update_cache: yes
     when: ansible_distribution=="RedHat"

   - name: make sure to run the apache
     service:
       enabled: yes
       name: apache2
       state: started
     when: ansible_distribution=="Ubuntu"

   - name: make sure to run the httpd
     service:
       enabled: yes
       name: httpd
       state: started
     when: ansible_distribution=="RedHat"

   - name: copy the index.html to /var/www/html
     copy:
       src: /etc/ansible/files/index.html
       dest: /var/www/html/index.html
                                                                                                                    



